/**
 * Plan feature matrix — single source of truth for tier-gated capabilities.
 *
 * This file is intentionally separate from `use-plan-limits.ts` (DB-driven
 * usage hook) and from `pricing.tsx` (DB-driven prices). It contains ONLY
 * feature flags and hard caps — no dollar amounts.
 *
 * Use `hasFeature(tier, "aiAssistant")` to gate UI/server logic by plan.
 * A cap of `-1` means unlimited.
 */

export const PLAN_FEATURES = {
  starter: {
    providerSeats: 1,
    activeClients: 500,
    services: 20,
    consentFormTemplates: 5,
    photoStorageGB: 10,
    reportTypes: 5,
    aiQueriesPerMonth: 0,
    smsCreditsIncluded: 50,
    emailsIncluded: 0,
    auditRetentionDays: 30,
    multiLocation: false,
    sso: false,
    aiAssistant: false,
    aiOptimizer: false,
    quickbooksSync: false,
    whatsapp: false,
    treatmentPlans: false,
    memberships: false,
    giftCards: false,
    promoCodes: false,
    customFields: false,
    clientPortal: false,
    waitlist: false,
    deposits: false,
    smartScheduling: false,
    photoAnnotations: false,
    watermarking: false,
    welcomeEmailSequence: false,
    twoWaySms: false,
    customizableInvoices: false,
    insuranceBilling: false,
  },
  professional: {
    providerSeats: 3,
    activeClients: -1,
    services: -1,
    consentFormTemplates: -1,
    photoStorageGB: 50,
    reportTypes: 18,
    aiQueriesPerMonth: 100,
    smsCreditsIncluded: 300,
    emailsIncluded: 5000,
    auditRetentionDays: 90,
    multiLocation: false,
    sso: false,
    aiAssistant: true,
    aiOptimizer: false,
    quickbooksSync: false,
    whatsapp: false,
    treatmentPlans: true,
    memberships: true,
    giftCards: true,
    promoCodes: true,
    customFields: true,
    clientPortal: true,
    waitlist: true,
    deposits: true,
    smartScheduling: true,
    photoAnnotations: true,
    watermarking: true,
    welcomeEmailSequence: true,
    twoWaySms: true,
    customizableInvoices: true,
    insuranceBilling: false,
  },
  growth: {
    providerSeats: 10,
    activeClients: -1,
    services: -1,
    consentFormTemplates: -1,
    photoStorageGB: 200,
    reportTypes: -1,
    aiQueriesPerMonth: 500,
    smsCreditsIncluded: 1000,
    emailsIncluded: 25000,
    auditRetentionDays: 365,
    multiLocation: true,
    sso: false,
    aiAssistant: true,
    aiOptimizer: true,
    quickbooksSync: true,
    whatsapp: true,
    treatmentPlans: true,
    memberships: true,
    giftCards: true,
    promoCodes: true,
    customFields: true,
    clientPortal: true,
    waitlist: true,
    deposits: true,
    smartScheduling: true,
    photoAnnotations: true,
    watermarking: true,
    welcomeEmailSequence: true,
    twoWaySms: true,
    customizableInvoices: true,
    insuranceBilling: false,
  },
  enterprise: {
    providerSeats: -1,
    activeClients: -1,
    services: -1,
    consentFormTemplates: -1,
    photoStorageGB: -1,
    reportTypes: -1,
    aiQueriesPerMonth: -1,
    smsCreditsIncluded: -1,
    emailsIncluded: -1,
    auditRetentionDays: -1,
    multiLocation: true,
    sso: true,
    aiAssistant: true,
    aiOptimizer: true,
    quickbooksSync: true,
    whatsapp: true,
    treatmentPlans: true,
    memberships: true,
    giftCards: true,
    promoCodes: true,
    customFields: true,
    clientPortal: true,
    waitlist: true,
    deposits: true,
    smartScheduling: true,
    photoAnnotations: true,
    watermarking: true,
    welcomeEmailSequence: true,
    twoWaySms: true,
    customizableInvoices: true,
    insuranceBilling: true,
  },
} as const;

export type PlanTier = keyof typeof PLAN_FEATURES;
export type PlanFeatures = typeof PLAN_FEATURES[PlanTier];

export function getPlanFeatures(tier: PlanTier): PlanFeatures {
  return PLAN_FEATURES[tier];
}

export function hasFeature<K extends keyof PlanFeatures>(
  tier: PlanTier,
  feature: K,
): PlanFeatures[K] {
  return PLAN_FEATURES[tier][feature];
}
