/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppStaffRouteImport } from './routes/app.staff'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppServicesRouteImport } from './routes/app.services'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPackagesRouteImport } from './routes/app.packages'
import { Route as AppMarketingRouteImport } from './routes/app.marketing'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppGiftcardsRouteImport } from './routes/app.giftcards'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCouponsRouteImport } from './routes/app.coupons'
import { Route as AppConsentRouteImport } from './routes/app.consent'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppBookingRouteImport } from './routes/app.booking'
import { Route as AppAutomationsRouteImport } from './routes/app.automations'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AppClientsClientIdRouteImport } from './routes/app.clients.$clientId'
import { Route as ApiPublicBookingRouteImport } from './routes/api.public.booking'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppGiftcardsRoute = AppGiftcardsRouteImport.update({
  id: '/giftcards',
  path: '/giftcards',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCouponsRoute = AppCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AppRoute,
} as any)
const AppConsentRoute = AppConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingRoute = AppBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AppClientsRoute,
} as any)
const ApiPublicBookingRoute = ApiPublicBookingRouteImport.update({
  id: '/api/public/booking',
  path: '/api/public/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/automations': typeof AppAutomationsRoute
  '/app/booking': typeof AppBookingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/consent': typeof AppConsentRoute
  '/app/coupons': typeof AppCouponsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/giftcards': typeof AppGiftcardsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/tasks': typeof AppTasksRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/book/$slug': typeof BookSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/automations': typeof AppAutomationsRoute
  '/app/booking': typeof AppBookingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/consent': typeof AppConsentRoute
  '/app/coupons': typeof AppCouponsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/giftcards': typeof AppGiftcardsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/tasks': typeof AppTasksRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/book/$slug': typeof BookSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/automations': typeof AppAutomationsRoute
  '/app/booking': typeof AppBookingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/consent': typeof AppConsentRoute
  '/app/coupons': typeof AppCouponsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/giftcards': typeof AppGiftcardsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/tasks': typeof AppTasksRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/book/$slug': typeof BookSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/automations'
    | '/app/booking'
    | '/app/calendar'
    | '/app/clients'
    | '/app/consent'
    | '/app/coupons'
    | '/app/dashboard'
    | '/app/giftcards'
    | '/app/inventory'
    | '/app/leads'
    | '/app/marketing'
    | '/app/packages'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/staff'
    | '/app/tasks'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/book/$slug'
    | '/email/unsubscribe'
    | '/api/public/booking'
    | '/app/clients/$clientId'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/automations'
    | '/app/booking'
    | '/app/calendar'
    | '/app/clients'
    | '/app/consent'
    | '/app/coupons'
    | '/app/dashboard'
    | '/app/giftcards'
    | '/app/inventory'
    | '/app/leads'
    | '/app/marketing'
    | '/app/packages'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/staff'
    | '/app/tasks'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/book/$slug'
    | '/email/unsubscribe'
    | '/api/public/booking'
    | '/app/clients/$clientId'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/automations'
    | '/app/booking'
    | '/app/calendar'
    | '/app/clients'
    | '/app/consent'
    | '/app/coupons'
    | '/app/dashboard'
    | '/app/giftcards'
    | '/app/inventory'
    | '/app/leads'
    | '/app/marketing'
    | '/app/packages'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/staff'
    | '/app/tasks'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/book/$slug'
    | '/email/unsubscribe'
    | '/api/public/booking'
    | '/app/clients/$clientId'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  BookSlugRoute: typeof BookSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicBookingRoute: typeof ApiPublicBookingRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/packages': {
      id: '/app/packages'
      path: '/packages'
      fullPath: '/app/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketing': {
      id: '/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/giftcards': {
      id: '/app/giftcards'
      path: '/giftcards'
      fullPath: '/app/giftcards'
      preLoaderRoute: typeof AppGiftcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coupons': {
      id: '/app/coupons'
      path: '/coupons'
      fullPath: '/app/coupons'
      preLoaderRoute: typeof AppCouponsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consent': {
      id: '/app/consent'
      path: '/consent'
      fullPath: '/app/consent'
      preLoaderRoute: typeof AppConsentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/booking': {
      id: '/app/booking'
      path: '/booking'
      fullPath: '/app/booking'
      preLoaderRoute: typeof AppBookingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automations': {
      id: '/app/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clients/$clientId': {
      id: '/app/clients/$clientId'
      path: '/$clientId'
      fullPath: '/app/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/api/public/booking': {
      id: '/api/public/booking'
      path: '/api/public/booking'
      fullPath: '/api/public/booking'
      preLoaderRoute: typeof ApiPublicBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsClientIdRoute: AppClientsClientIdRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppRouteChildren {
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppBookingRoute: typeof AppBookingRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppConsentRoute: typeof AppConsentRoute
  AppCouponsRoute: typeof AppCouponsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGiftcardsRoute: typeof AppGiftcardsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppPackagesRoute: typeof AppPackagesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppTasksRoute: typeof AppTasksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationsRoute: AppAutomationsRoute,
  AppBookingRoute: AppBookingRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppConsentRoute: AppConsentRoute,
  AppCouponsRoute: AppCouponsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGiftcardsRoute: AppGiftcardsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppPackagesRoute: AppPackagesRoute,
  AppReportsRoute: AppReportsRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppTasksRoute: AppTasksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  BookSlugRoute: BookSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicBookingRoute: ApiPublicBookingRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
