/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AppTreatmentPlansRouteImport } from './routes/app.treatment-plans'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppStaffRouteImport } from './routes/app.staff'
import { Route as AppSoapNotesRouteImport } from './routes/app.soap-notes'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppServicesRouteImport } from './routes/app.services'
import { Route as AppReviewsRouteImport } from './routes/app.reviews'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppReferralsRouteImport } from './routes/app.referrals'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppPackagesRouteImport } from './routes/app.packages'
import { Route as AppMembershipsRouteImport } from './routes/app.memberships'
import { Route as AppMarketingRouteImport } from './routes/app.marketing'
import { Route as AppLoyaltyRouteImport } from './routes/app.loyalty'
import { Route as AppLocationsRouteImport } from './routes/app.locations'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppInjectionMappingRouteImport } from './routes/app.injection-mapping'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppGiftcardsRouteImport } from './routes/app.giftcards'
import { Route as AppEmailLogRouteImport } from './routes/app.email-log'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCouponsRouteImport } from './routes/app.coupons'
import { Route as AppConsentRouteImport } from './routes/app.consent'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCheckinRouteImport } from './routes/app.checkin'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppBookingRouteImport } from './routes/app.booking'
import { Route as AppBeforeAfterRouteImport } from './routes/app.before-after'
import { Route as AppAutomationsRouteImport } from './routes/app.automations'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AppSettingsBillingRouteImport } from './routes/app.settings.billing'
import { Route as AppClientsClientIdRouteImport } from './routes/app.clients.$clientId'
import { Route as ApiPublicBookingRouteImport } from './routes/api.public.booking'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTreatmentPlansRoute = AppTreatmentPlansRouteImport.update({
  id: '/treatment-plans',
  path: '/treatment-plans',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSoapNotesRoute = AppSoapNotesRouteImport.update({
  id: '/soap-notes',
  path: '/soap-notes',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppMembershipsRoute = AppMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppLoyaltyRoute = AppLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppInjectionMappingRoute = AppInjectionMappingRouteImport.update({
  id: '/injection-mapping',
  path: '/injection-mapping',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppGiftcardsRoute = AppGiftcardsRouteImport.update({
  id: '/giftcards',
  path: '/giftcards',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailLogRoute = AppEmailLogRouteImport.update({
  id: '/email-log',
  path: '/email-log',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCouponsRoute = AppCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AppRoute,
} as any)
const AppConsentRoute = AppConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingRoute = AppBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AppRoute,
} as any)
const AppBeforeAfterRoute = AppBeforeAfterRouteImport.update({
  id: '/before-after',
  path: '/before-after',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AppClientsRoute,
} as any)
const ApiPublicBookingRoute = ApiPublicBookingRouteImport.update({
  id: '/api/public/booking',
  path: '/api/public/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/ai': typeof AppAiRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/before-after': typeof AppBeforeAfterRoute
  '/app/booking': typeof AppBookingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/consent': typeof AppConsentRoute
  '/app/coupons': typeof AppCouponsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/email-log': typeof AppEmailLogRoute
  '/app/giftcards': typeof AppGiftcardsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/injection-mapping': typeof AppInjectionMappingRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/memberships': typeof AppMembershipsRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/pos': typeof AppPosRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/soap-notes': typeof AppSoapNotesRoute
  '/app/staff': typeof AppStaffRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/treatment-plans': typeof AppTreatmentPlansRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/book/$slug': typeof BookSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/ai': typeof AppAiRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/before-after': typeof AppBeforeAfterRoute
  '/app/booking': typeof AppBookingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/consent': typeof AppConsentRoute
  '/app/coupons': typeof AppCouponsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/email-log': typeof AppEmailLogRoute
  '/app/giftcards': typeof AppGiftcardsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/injection-mapping': typeof AppInjectionMappingRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/memberships': typeof AppMembershipsRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/pos': typeof AppPosRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/soap-notes': typeof AppSoapNotesRoute
  '/app/staff': typeof AppStaffRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/treatment-plans': typeof AppTreatmentPlansRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/book/$slug': typeof BookSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/ai': typeof AppAiRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/before-after': typeof AppBeforeAfterRoute
  '/app/booking': typeof AppBookingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/consent': typeof AppConsentRoute
  '/app/coupons': typeof AppCouponsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/email-log': typeof AppEmailLogRoute
  '/app/giftcards': typeof AppGiftcardsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/injection-mapping': typeof AppInjectionMappingRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/memberships': typeof AppMembershipsRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/pos': typeof AppPosRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/soap-notes': typeof AppSoapNotesRoute
  '/app/staff': typeof AppStaffRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/treatment-plans': typeof AppTreatmentPlansRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/book/$slug': typeof BookSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/unsubscribe'
    | '/app/ai'
    | '/app/automations'
    | '/app/before-after'
    | '/app/booking'
    | '/app/calendar'
    | '/app/checkin'
    | '/app/clients'
    | '/app/consent'
    | '/app/coupons'
    | '/app/dashboard'
    | '/app/email-log'
    | '/app/giftcards'
    | '/app/inbox'
    | '/app/injection-mapping'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/leads'
    | '/app/locations'
    | '/app/loyalty'
    | '/app/marketing'
    | '/app/memberships'
    | '/app/packages'
    | '/app/pos'
    | '/app/referrals'
    | '/app/reports'
    | '/app/reviews'
    | '/app/services'
    | '/app/settings'
    | '/app/soap-notes'
    | '/app/staff'
    | '/app/tasks'
    | '/app/treatment-plans'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/book/$slug'
    | '/email/unsubscribe'
    | '/api/public/booking'
    | '/app/clients/$clientId'
    | '/app/settings/billing'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/unsubscribe'
    | '/app/ai'
    | '/app/automations'
    | '/app/before-after'
    | '/app/booking'
    | '/app/calendar'
    | '/app/checkin'
    | '/app/clients'
    | '/app/consent'
    | '/app/coupons'
    | '/app/dashboard'
    | '/app/email-log'
    | '/app/giftcards'
    | '/app/inbox'
    | '/app/injection-mapping'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/leads'
    | '/app/locations'
    | '/app/loyalty'
    | '/app/marketing'
    | '/app/memberships'
    | '/app/packages'
    | '/app/pos'
    | '/app/referrals'
    | '/app/reports'
    | '/app/reviews'
    | '/app/services'
    | '/app/settings'
    | '/app/soap-notes'
    | '/app/staff'
    | '/app/tasks'
    | '/app/treatment-plans'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/book/$slug'
    | '/email/unsubscribe'
    | '/api/public/booking'
    | '/app/clients/$clientId'
    | '/app/settings/billing'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/unsubscribe'
    | '/app/ai'
    | '/app/automations'
    | '/app/before-after'
    | '/app/booking'
    | '/app/calendar'
    | '/app/checkin'
    | '/app/clients'
    | '/app/consent'
    | '/app/coupons'
    | '/app/dashboard'
    | '/app/email-log'
    | '/app/giftcards'
    | '/app/inbox'
    | '/app/injection-mapping'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/leads'
    | '/app/locations'
    | '/app/loyalty'
    | '/app/marketing'
    | '/app/memberships'
    | '/app/packages'
    | '/app/pos'
    | '/app/referrals'
    | '/app/reports'
    | '/app/reviews'
    | '/app/services'
    | '/app/settings'
    | '/app/soap-notes'
    | '/app/staff'
    | '/app/tasks'
    | '/app/treatment-plans'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/book/$slug'
    | '/email/unsubscribe'
    | '/api/public/booking'
    | '/app/clients/$clientId'
    | '/app/settings/billing'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  BookSlugRoute: typeof BookSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicBookingRoute: typeof ApiPublicBookingRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/treatment-plans': {
      id: '/app/treatment-plans'
      path: '/treatment-plans'
      fullPath: '/app/treatment-plans'
      preLoaderRoute: typeof AppTreatmentPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/soap-notes': {
      id: '/app/soap-notes'
      path: '/soap-notes'
      fullPath: '/app/soap-notes'
      preLoaderRoute: typeof AppSoapNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reviews': {
      id: '/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referrals': {
      id: '/app/referrals'
      path: '/referrals'
      fullPath: '/app/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/packages': {
      id: '/app/packages'
      path: '/packages'
      fullPath: '/app/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/memberships': {
      id: '/app/memberships'
      path: '/memberships'
      fullPath: '/app/memberships'
      preLoaderRoute: typeof AppMembershipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketing': {
      id: '/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/loyalty': {
      id: '/app/loyalty'
      path: '/loyalty'
      fullPath: '/app/loyalty'
      preLoaderRoute: typeof AppLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations': {
      id: '/app/locations'
      path: '/locations'
      fullPath: '/app/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/injection-mapping': {
      id: '/app/injection-mapping'
      path: '/injection-mapping'
      fullPath: '/app/injection-mapping'
      preLoaderRoute: typeof AppInjectionMappingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/giftcards': {
      id: '/app/giftcards'
      path: '/giftcards'
      fullPath: '/app/giftcards'
      preLoaderRoute: typeof AppGiftcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/email-log': {
      id: '/app/email-log'
      path: '/email-log'
      fullPath: '/app/email-log'
      preLoaderRoute: typeof AppEmailLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coupons': {
      id: '/app/coupons'
      path: '/coupons'
      fullPath: '/app/coupons'
      preLoaderRoute: typeof AppCouponsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consent': {
      id: '/app/consent'
      path: '/consent'
      fullPath: '/app/consent'
      preLoaderRoute: typeof AppConsentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkin': {
      id: '/app/checkin'
      path: '/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/booking': {
      id: '/app/booking'
      path: '/booking'
      fullPath: '/app/booking'
      preLoaderRoute: typeof AppBookingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/before-after': {
      id: '/app/before-after'
      path: '/before-after'
      fullPath: '/app/before-after'
      preLoaderRoute: typeof AppBeforeAfterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automations': {
      id: '/app/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/billing': {
      id: '/app/settings/billing'
      path: '/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/clients/$clientId': {
      id: '/app/clients/$clientId'
      path: '/$clientId'
      fullPath: '/app/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/api/public/booking': {
      id: '/api/public/booking'
      path: '/api/public/booking'
      fullPath: '/api/public/booking'
      preLoaderRoute: typeof ApiPublicBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsClientIdRoute: AppClientsClientIdRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsBillingRoute: AppSettingsBillingRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppBeforeAfterRoute: typeof AppBeforeAfterRoute
  AppBookingRoute: typeof AppBookingRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCheckinRoute: typeof AppCheckinRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppConsentRoute: typeof AppConsentRoute
  AppCouponsRoute: typeof AppCouponsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmailLogRoute: typeof AppEmailLogRoute
  AppGiftcardsRoute: typeof AppGiftcardsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppInjectionMappingRoute: typeof AppInjectionMappingRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppLoyaltyRoute: typeof AppLoyaltyRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppMembershipsRoute: typeof AppMembershipsRoute
  AppPackagesRoute: typeof AppPackagesRoute
  AppPosRoute: typeof AppPosRoute
  AppReferralsRoute: typeof AppReferralsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReviewsRoute: typeof AppReviewsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSoapNotesRoute: typeof AppSoapNotesRoute
  AppStaffRoute: typeof AppStaffRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTreatmentPlansRoute: typeof AppTreatmentPlansRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAutomationsRoute: AppAutomationsRoute,
  AppBeforeAfterRoute: AppBeforeAfterRoute,
  AppBookingRoute: AppBookingRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCheckinRoute: AppCheckinRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppConsentRoute: AppConsentRoute,
  AppCouponsRoute: AppCouponsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmailLogRoute: AppEmailLogRoute,
  AppGiftcardsRoute: AppGiftcardsRoute,
  AppInboxRoute: AppInboxRoute,
  AppInjectionMappingRoute: AppInjectionMappingRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppLoyaltyRoute: AppLoyaltyRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppMembershipsRoute: AppMembershipsRoute,
  AppPackagesRoute: AppPackagesRoute,
  AppPosRoute: AppPosRoute,
  AppReferralsRoute: AppReferralsRoute,
  AppReportsRoute: AppReportsRoute,
  AppReviewsRoute: AppReviewsRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSoapNotesRoute: AppSoapNotesRoute,
  AppStaffRoute: AppStaffRoute,
  AppTasksRoute: AppTasksRoute,
  AppTreatmentPlansRoute: AppTreatmentPlansRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  BookSlugRoute: BookSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicBookingRoute: ApiPublicBookingRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
